//
//  BalancePresenter.swift
//  BankApp
//
//  Created by user149157 on 6/7/20.
//  Copyright (c) 2020 mhonorio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BalancePresentationLogic
{
  func presentSomething(response: Balance.Something.Response)
}

class BalancePresenter: BalancePresentationLogic
{
  weak var viewController: BalanceDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Balance.Something.Response)
  {
    let viewModel = Balance.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
