//
//  BalanceInteractor.swift
//  BankApp
//
//  Created by user149157 on 6/7/20.
//  Copyright (c) 2020 mhonorio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BalanceBusinessLogic
{
  func doSomething(request: Balance.Something.Request)
}

protocol BalanceDataStore
{
  //var name: String { get set }
}

class BalanceInteractor: BalanceBusinessLogic, BalanceDataStore
{
  var presenter: BalancePresentationLogic?
  var worker: BalanceWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Balance.Something.Request)
  {
    worker = BalanceWorker()
    worker?.doSomeWork()
    
    let response = Balance.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
