//
//  LoginWorker.swift
//  BankApp
//
//  Created by user149157 on 6/7/20.
//  Copyright (c) 2020 mhonorio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
  func doSomeWork()
  {
    
  }
}
