# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BankApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '= 4.7.2'
  pod 'SwiftyJSON', '= 4.2.0'
  pod 'SnapKit'

  target 'BankAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
